version: "3.8"

services:
  wtc-backend:
    image: wtc-backend:latest
    build: "."
    restart: always
    ports:
      - "12000:12000"
    networks:
      - wtc
    env_file:
      - ".env"

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    hostname: mongo
    volumes:
      - mongodb-data:/data/db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - wtc
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - wtc
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  wtc:

volumes:
  mongodb-data: